#version 450

layout( local_size_x = 8, local_size_y = 8 ) in;

layout( binding = 0 ) uniform ubo {
    float power;
};
layout( r11f_g11f_b10f, binding = 1 ) uniform image2D img[ 2 ];

void main()
{
    ivec2 xy = ivec2( gl_GlobalInvocationID.xy );
    vec4 pixelIn = imageLoad( img[ 0 ], xy );
    vec3 pixelOut = pow( pixelIn.rgb, vec3( power ) );
    imageStore( img[ 1 ], xy, vec4( pixelOut, 1.0 ) );
}
